export
const countries = [
    "China",
    "United States",
    "Japan",
    "Brazil",
    "Germany",
    "India",
    "Russia",
    "United Kingdom",
    "France",
    "Nigeria",
    "South Korea",
    "Turkey",
    "Mexico",
    "Italy",
    "Spain",
    "Canada",
    "Vietnam",
    "Colombia",
    "Poland",
    "Pakistan",
    "Egypt",
    "Indonesia",
    "Thailand",
    "Taiwan",
    "Australia",
    "Malaysia",
    "Ukraine",
    "Netherlands",
    "Argentina",
    "Morocco",
    "Saudi Arabia",
    "Peru",
    "Venezuela",
    "Sweden",
    "Philippines",
    "Iran",
    "Belgium",
    "Romania",
    "Chile",
    "Czech Republic",
    "Hungary",
    "Austria",
    "Switzerland",
    "Kazakhstan",
    "Portugal",
    "Greece",
    "Hong Kong",
    "Denmark",
    "Algeria",
    "Uzbekistan",
    "Israel",
    "Palestina",
    "Finland",
    "Syria",
    "Belarus",
    "Norway",
    "South Africa",
    "Sudan",
    "Serbia",
    "Slovakia",
    "Kenya",
    "Azerbaijan",
    "Tunisia",
    "United Arab Emirates",
    "New Zealand",
    "Bulgaria",
    "Ecuador",
    "Singapore",
    "Uganda",
    "Ireland",
    "Dominican Republic",
    "Yemen",
    "Guatemala",
    "Croatia",
    "Kyrgyzstan",
    "Lithuania",
    "Senegal",
    "Sri Lanka",
    "Jordan",
    "Cuba",
    "Jamaica",
    "Latvia",
    "Costa Rica",
    "Oman",
    "Bosnia and Herzegovina",
    "Zimbabwe",
    "Uruguay",
    "West Bank",
    "Gaza Strip",
    "Albania",
    "Georgia",
    "Slovenia",
    "Ghana",
    "Moldova",
    "Paraguay",
    "Bolivia",
    "Kuwait",
    "Republic of Macedonia",
    "Haiti",
    "Puerto Rico",
    "Lebanon",
    "Afghanistan",
    "Estonia",
    "Cote d'Ivoire",
    "Panama",
    "Zambia",
    "Cameroon",
    "El Salvador",
    "Honduras",
    "Malawi",
    "Tajikistan",
    "Tanzania",
    "Bangladesh",
    "Mozambique",
    "Angola",
    "Trinidad and Tobago",
    "Nepal",
    "Qatar",
    "Rwanda",
    "Ethiopia",
    "Cyprus",
    "Luxembourg",
    "Bahrain",
    "Togo",
    "Libya",
    "Mongolia",
    "Iraq",
    "Madagascar",
    "Brunei",
    "Iceland",
    "Laos",
    "Mauritius",
    "Democratic Republic of the Congo",
    "Montenegro",
    "Macau",
    "Mali",
    "Congo, Republic of the",
    "Malta",
    "Armenia",
    "Benin",
    "Eritrea",
    "Nicaragua",
    "Guyana",
    "Barbados",
    "Burkina Faso",
    "Chad",
    "Suriname",
    "Burundi",
    "Cape Verde",
    "Saint Lucia",
    "The Gambia",
    "Namibia",
    "Papua New Guinea",
    "French Polynesia",
    "Botswana",
    "Niger",
    "The Bahamas",
    "Fiji",
    "Burma",
    "Somalia",
    "Gabon",
    "Guinea",
    "Swaziland",
    "Guam",
    "Maldives",
    "New Caledonia",
    "Turkmenistan",
    "Cambodia",
    "Lesotho",
    "Saint Vincent and the Grenadines",
    "Mauritania",
    "Andorra",
    "Antigua and Barbuda",
    "Bermuda",
    "Bhutan",
    "Guernsey",
    "Faroe Islands",
    "Guinea-Bissau",
    "Greenland",
    "Belize",
    "Seychelles",
    "Virgin Islands",
    "Jersey",
    "Dominica",
    "Sao Tome and Principe",
    "Djibouti",
    "Grenada",
    "Comoros",
    "Aruba",
    "Monaco",
    "Liechtenstein",
    "Cayman Islands",
    "Central African Republic",
    "Gibraltar",
    "Liberia",
    "San Marino",
    "Saint Kitts and Nevis",
    "Federated States of Micronesia",
    "Vanuatu",
    "Sierra Leone",
    "Equatorial Guinea",
    "Solomon Islands",
    "Samoa",
    "Tonga",
    "Kiribati",
    "Cook Islands",
    "Tuvalu",
    "British Virgin Islands",
    "Anguilla",
    "Falkland Islands (Islas Malvinas)",
    "Marshall Islands",
    "East Timor",
    "Wallis and Futuna",
    "Montserrat",
    "Niue",
    "Saint Helena",
    "Saint Helena, Ascension, and Tristan da Cunha",
    "Tokelau",
    "Christmas Island"
]